
INSERT INTO public.activities (title, description, type, start_date, end_date, location, total_slots, available_slots, status)
VALUES
  ('Oficina de Introdução à Programação com Python', 'Aprenda os fundamentos de programação usando Python! Nesta oficina prática, você vai dar seus primeiros passos no mundo da programação, criando pequenos programas e entendendo lógica computacional. Não é necessário conhecimento prévio.', 'oficina', '2026-04-10T14:00:00Z', '2026-04-10T17:00:00Z', 'Laboratório de Informática - Bloco A', 30, 12, 'aberta'),
  ('Minicurso de Desenvolvimento Web com React', 'Um minicurso completo sobre desenvolvimento de aplicações web modernas usando React, TypeScript e Tailwind CSS. Você vai construir uma aplicação real do zero ao deploy.', 'minicurso', '2026-04-15T09:00:00Z', '2026-04-17T12:00:00Z', 'Sala 201 - Bloco B', 25, 0, 'aberta'),
  ('Palestra: Mulheres na Tecnologia - Desafios e Conquistas', 'Uma palestra inspiradora com profissionais que compartilham suas trajetórias na área de tecnologia, discutindo desafios, oportunidades e dicas para quem está começando.', 'palestra', '2026-04-20T19:00:00Z', '2026-04-20T21:00:00Z', 'Auditório Principal', 100, 45, 'aberta'),
  ('Oficina de Robótica com Arduino', 'Construa seu primeiro robô! Nesta oficina prática, vamos montar circuitos e programar Arduino para criar projetos interativos. Material incluso.', 'oficina', '2026-03-05T14:00:00Z', '2026-03-05T17:00:00Z', 'Laboratório de Eletrônica', 20, 0, 'encerrada'),
  ('Palestra: Inteligência Artificial no Dia a Dia', 'Entenda como a IA está transformando o mundo e como você pode se preparar para essa revolução tecnológica.', 'palestra', '2026-04-25T18:00:00Z', '2026-04-25T20:00:00Z', 'Online (Google Meet)', 200, 150, 'aberta'),
  ('Minicurso de Design de Interfaces (UI/UX)', 'Aprenda os princípios de design de interfaces centradas no usuário usando Figma. Crie protótipos navegáveis e aprenda sobre pesquisa com usuários.', 'minicurso', '2026-05-02T09:00:00Z', '2026-05-04T12:00:00Z', 'Laboratório de Informática - Bloco C', 20, 8, 'aberta');
