// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wivoneicusyqxfjfjpiq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indpdm9uZWljdXN5cXhmamZqcGlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM3MDUzNDgsImV4cCI6MjA4OTI4MTM0OH0.CIU-jF1gsufCL503YJD2H-wHu6T81QXFh7AwQbD7R8U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});